# fly.toml app configuration file generated for itopt-slack-board on 2023-05-07T11:19:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itopt-slack-board"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/up"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
