# fly.toml app configuration file generated for itopt-slack-board on 2023-05-07T11:19:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itopt-slack-board"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
