name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 [INIT] Clone repository
        uses: actions/checkout@v3

      - name: 🚀 [SET] Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 [DEPLOY] Deploy app
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
